export type Course = {
  id: number;
  title: string;
  subject: string;
  grade: string;
  teacher: string;
  rating: number;
  reviews: number;
  price: number;
  duration: string;
  mode: string;
  description: string;
  icon: string;
};

export const courses: Course[] = [
  {
    id: 1,
    title: "Python Programming for Beginners",
    subject: "Coding",
    grade: "Grade 6-8",
    teacher: "Aarav Sharma",
    rating: 4.9,
    reviews: 128,
    price: 1499,
    duration: "8 weeks",
    mode: "Online",
    description: "Learn Python fundamentals through fun projects.",
    icon: "💻",
  },
  {
    id: 2,
    title: "Creative Drawing & Painting",
    subject: "Arts",
    grade: "Grade 3-5",
    teacher: "Meera Kapoor",
    rating: 4.8,
    reviews: 96,
    price: 999,
    duration: "6 weeks",
    mode: "Online",
    description: "Develop creativity through drawing and painting.",
    icon: "🎨",
  },
  {
    id: 3,
    title: "Mathematics Mastery",
    subject: "Mathematics",
    grade: "Grade 6-8",
    teacher: "Rohan Mehta",
    rating: 4.7,
    reviews: 84,
    price: 1299,
    duration: "10 weeks",
    mode: "Online",
    description: "Build strong mathematical concepts and confidence.",
    icon: "🔢",
  },
  {
    id: 4,
    title: "English Communication Skills",
    subject: "English",
    grade: "Grade 3-5",
    teacher: "Priya Shah",
    rating: 4.6,
    reviews: 72,
    price: 899,
    duration: "6 weeks",
    mode: "Online",
    description: "Improve vocabulary, grammar and communication.",
    icon: "📚",
  },
  {
    id: 5,
    title: "Robotics for Young Innovators",
    subject: "Coding",
    grade: "Grade 9-12",
    teacher: "Vikram Joshi",
    rating: 4.9,
    reviews: 156,
    price: 2499,
    duration: "12 weeks",
    mode: "Offline",
    description: "Build robots while learning electronics and coding.",
    icon: "🤖",
  },
  {
    id: 6,
    title: "Junior Guitar Academy",
    subject: "Music",
    grade: "Grade 3-5",
    teacher: "Kabir Singh",
    rating: 4.5,
    reviews: 61,
    price: 1199,
    duration: "8 weeks",
    mode: "Online",
    description: "Learn guitar basics with interactive lessons.",
    icon: "🎸",
  },
  {
    id: 7,
    title: "Advanced JavaScript",
    subject: "Coding",
    grade: "Grade 9-12",
    teacher: "Neha Patel",
    rating: 4.8,
    reviews: 113,
    price: 1999,
    duration: "10 weeks",
    mode: "Online",
    description: "Explore JavaScript through real-world projects.",
    icon: "⚡",
  },
  {
    id: 8,
    title: "Science Explorers",
    subject: "Science",
    grade: "Grade 3-5",
    teacher: "Ananya Rao",
    rating: 4.7,
    reviews: 89,
    price: 1099,
    duration: "8 weeks",
    mode: "Offline",
    description: "Discover science through experiments and activities.",
    icon: "🔬",
  },
  {
    id: 9,
    title: "Physics Fundamentals",
    subject: "Science",
    grade: "Grade 9-12",
    teacher: "Aditya Nair",
    rating: 4.9,
    reviews: 143,
    price: 1799,
    duration: "12 weeks",
    mode: "Online",
    description: "Understand physics with practical examples.",
    icon: "🧪",
  },
  {
    id: 10,
    title: "Chess Champions",
    subject: "Sports",
    grade: "Grade 6-8",
    teacher: "Arjun Malhotra",
    rating: 4.8,
    reviews: 118,
    price: 799,
    duration: "6 weeks",
    mode: "Online",
    description: "Improve strategy, concentration and problem solving.",
    icon: "♟️",
  },
  {
    id: 11,
    title: "Digital Illustration",
    subject: "Arts",
    grade: "Grade 9-12",
    teacher: "Ishita Verma",
    rating: 4.6,
    reviews: 54,
    price: 1599,
    duration: "8 weeks",
    mode: "Online",
    description: "Learn digital art and illustration techniques.",
    icon: "🖌️",
  },
  {
    id: 12,
    title: "Public Speaking for Kids",
    subject: "English",
    grade: "Grade 6-8",
    teacher: "Simran Kaur",
    rating: 4.7,
    reviews: 77,
    price: 899,
    duration: "6 weeks",
    mode: "Online",
    description: "Build confidence and become a better speaker.",
    icon: "🎤",
  },
  {
    id: 13,
    title: "Web Development Basics",
    subject: "Coding",
    grade: "Grade 9-12",
    teacher: "Rahul Desai",
    rating: 4.8,
    reviews: 134,
    price: 2199,
    duration: "12 weeks",
    mode: "Online",
    description: "Create websites using HTML, CSS and JavaScript.",
    icon: "🌐",
  },
  {
    id: 14,
    title: "Creative Writing Club",
    subject: "English",
    grade: "Grade 6-8",
    teacher: "Pooja Iyer",
    rating: 4.5,
    reviews: 49,
    price: 699,
    duration: "6 weeks",
    mode: "Online",
    description: "Turn ideas into stories, poems and creative writing.",
    icon: "✍️",
  },
  {
    id: 15,
    title: "Mental Maths",
    subject: "Mathematics",
    grade: "Grade 3-5",
    teacher: "Karan Gupta",
    rating: 4.6,
    reviews: 67,
    price: 749,
    duration: "5 weeks",
    mode: "Online",
    description: "Develop faster calculation and problem-solving skills.",
    icon: "🧮",
  },
  {
    id: 16,
    title: "Basketball Skills",
    subject: "Sports",
    grade: "Grade 6-8",
    teacher: "Manav Singh",
    rating: 4.7,
    reviews: 45,
    price: 1299,
    duration: "8 weeks",
    mode: "Offline",
    description: "Learn basketball fundamentals and teamwork.",
    icon: "🏀",
  },
  {
    id: 17,
    title: "Keyboard & Music Basics",
    subject: "Music",
    grade: "Grade 3-5",
    teacher: "Nisha Jain",
    rating: 4.8,
    reviews: 91,
    price: 1099,
    duration: "8 weeks",
    mode: "Online",
    description: "Start your musical journey with keyboard lessons.",
    icon: "🎹",
  },
  {
    id: 18,
    title: "AI & Machine Learning for Teens",
    subject: "Coding",
    grade: "Grade 9-12",
    teacher: "Dev Malhotra",
    rating: 4.9,
    reviews: 187,
    price: 2999,
    duration: "12 weeks",
    mode: "Online",
    description: "An introduction to AI and machine learning.",
    icon: "🧠",
  },
];